'use client'

import { colors } from '@/lib/design-tokens'
import { formatUtcDate, formatUtcDateTime } from '@/lib/report'
import type { ReportPayload } from '@/lib/api'
import { ReportCover } from './ReportCover'
import { ExecutiveSummary } from './ExecutiveSummary'
import { TrendChart } from './TrendChart'
import { DistributionBars } from './DistributionBars'
import { SessionsTable } from './SessionsTable'
import { ReliabilitySection } from './ReliabilitySection'
import { InsightsSection } from './InsightsSection'

/**
 * The printable report. Everything inside `.report-print-area` is what ends up
 * in the PDF (print CSS hides the app chrome and reveals the cover).
 */
export function ReportView({
  report,
  periodLabel,
}: {
  report: ReportPayload
  periodLabel: string
}) {
  const p = report.period
  return (
    // Top-down hierarchy: summary → trend → breakdown/reliability → sessions →
    // insights. Generous vertical rhythm keeps sections scannable.
    <div className="report-print-area space-y-8">
      <ReportCover report={report} periodLabel={periodLabel} />

      {/* On-screen section title (the cover replaces this in print). */}
      <div className="report-screen-heading">
        <h2 className="text-base font-semibold" style={{ color: colors.textStrong }}>
          {report.agent}
        </h2>
        <p className="text-xs mt-0.5" style={{ color: colors.textFaint }}>
          {periodLabel} · {formatUtcDate(p.from)} – {formatUtcDate(p.to)} (UTC) · generated{' '}
          {formatUtcDateTime(report.generated_at)} UTC
        </p>
      </div>

      <ExecutiveSummary summary={report.summary} />

      <TrendChart buckets={report.timeseries} granularity={p.granularity} />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 report-avoid-break">
        <DistributionBars
          distribution={report.distribution.event_distribution}
          transitions={report.distribution.transitions}
        />
        <ReliabilitySection drift={report.drift} summary={report.summary} />
      </div>

      <SessionsTable sessions={report.sessions} />

      <InsightsSection items={report.recommendations} />

      <p className="report-footer-note text-xs pt-2" style={{ color: colors.textFaint }}>
        Generated by ZizkaDB · v{report.report_version} ·{' '}
        {formatUtcDateTime(report.generated_at)} UTC · all times UTC
      </p>
    </div>
  )
}
