import os
from fastapi import Security
from services.exceptions import forbidden, unauthorized
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from services.auth import verify_api_key, decode_access_token

bearer = HTTPBearer()

# Dev key: set DEV_API_KEY in .env for self-hosted local development.
# Any request with this token is accepted without a DB lookup.
# Never set this in production managed cloud.
_DEV_API_KEY = os.getenv("DEV_API_KEY", "")
_IS_PRODUCTION = os.getenv("ENV", "development") == "production"
# SDK/MCP default vs legacy self-host .env — accept both in local dev only.
_KNOWN_DEV_KEYS = frozenset({"zizkadb_dev_local", "agdb_dev_local"})

# Same IDs as /v1/auth/dev-token (core/api/auth.py)
_DEV_TENANT_ID = "00000000-0000-0000-0000-000000000001"
_DEV_USER_ID = "00000000-0000-0000-0000-000000000001"

_DEV_TENANT = {
    "tenant_id": _DEV_TENANT_ID,
    "user_id": _DEV_USER_ID,
}

# Actionable 401 message for a rejected API key. New integrators (especially
# self-hosters) otherwise just see "Invalid API key" with no idea what to check,
# so point them at the right place to get a key for the deployment they hit.
_INVALID_API_KEY_MESSAGE = (
    "Invalid API key. Ensure you're using a valid API key for this deployment. "
    "Cloud API keys are issued from the dashboard, while self-hosted instances use "
    "keys generated by that instance."
)


def looks_like_jwt(token: str) -> bool:
    """JWTs use three dot-separated segments; API keys do not."""
    return token.count(".") == 2


async def resolve_api_key_tenant(token: str) -> dict | None:
    """Verify API key by hash.

    Works for every key ever issued on managed cloud, including legacy
    ``agdb_live_...`` keys from the AgentDB era and new ``zizkadb_live_...``
    keys. Prefix is not checked — only the SHA-256 hash in ``api_keys``.
    """
    if looks_like_jwt(token):
        return None
    return await verify_api_key(token)


_AGENT_KEY_MISMATCH = (
    "This API key is already associated with another agent and cannot be used "
    "by this agent. Use the API key that belongs to this agent, or create "
    "another API key if your plan allows it."
)


def _raise_agent_mismatch() -> None:
    raise forbidden(detail=_AGENT_KEY_MISMATCH)


async def assert_agent_allowed(tenant: dict, agent_id: str) -> None:
    """Enforce one API key = one agent.

    JWT dashboard sessions and the local dev key have no ``key_id`` and are
    not bound. Keys already bound to an agent are compared in memory.
    Unassigned keys (``agent_id`` NULL) are claimed atomically on first use.
    """
    scoped = tenant.get("agent_id")
    if scoped:
        if scoped != agent_id:
            _raise_agent_mismatch()
        return

    key_id = tenant.get("key_id")
    if not key_id:
        return

    from services.api_keys import claim_unassigned_api_key

    bound = await claim_unassigned_api_key(
        key_id=key_id,
        tenant_id=tenant["tenant_id"],
        agent_id=agent_id,
    )
    if bound is None:
        raise unauthorized(detail=_INVALID_API_KEY_MESSAGE)
    tenant["agent_id"] = bound
    if bound != agent_id:
        _raise_agent_mismatch()


def _dev_key_accepted(token: str) -> bool:
    if _IS_PRODUCTION:
        return False
    if _DEV_API_KEY:
        if token == _DEV_API_KEY:
            return True
        # Transition: old infra/.env used agdb_dev_local; SDK/MCP use zizkadb_dev_local.
        if _DEV_API_KEY in _KNOWN_DEV_KEYS and token in _KNOWN_DEV_KEYS:
            return True
        return False
    return token in _KNOWN_DEV_KEYS


def dashboard_session_dependency(forbid_detail: str):
    """Build a JWT-only FastAPI dependency for dashboard-managed actions.

    Rejects API-key auth so a scoped agent key cannot perform dashboard-only
    actions (e.g. minting new keys), and guarantees a ``user_id``/plan context.
    ``forbid_detail`` is the 403 message shown when an API key is used instead of
    a dashboard session. Returns a dependency that yields ``{tenant_id, user_id}``.

    Single implementation reused by every JWT-only router (auth, agents, account,
    settings) so the auth logic can never drift between them.
    """

    async def _require_dashboard_session(
        credentials: HTTPAuthorizationCredentials = Security(bearer),
    ) -> dict:
        token = credentials.credentials
        if await resolve_api_key_tenant(token):
            raise forbidden(detail=forbid_detail)
        try:
            payload = decode_access_token(token)
            return {
                "tenant_id": payload["tenant_id"],
                "user_id": payload["sub"],
            }
        except Exception:
            raise unauthorized(detail="Invalid token")

    return _require_dashboard_session


# Default dependency for API-key management routes (auth, agents).
require_dashboard_session = dashboard_session_dependency(
    "Sign in to the dashboard to manage API keys"
)


async def get_tenant(
    credentials: HTTPAuthorizationCredentials = Security(bearer),
) -> dict:
    """Validate API key or JWT and return tenant context."""
    token = credentials.credentials

    # Dev key bypass (self-hosted local development only)
    if _dev_key_accepted(token):
        return _DEV_TENANT

    # API key (verified by hash, not prefix)
    tenant = await resolve_api_key_tenant(token)
    if tenant:
        return tenant

    if not looks_like_jwt(token):
        raise unauthorized(detail=_INVALID_API_KEY_MESSAGE)

    # JWT (dashboard sessions)
    try:
        payload = decode_access_token(token)
        return {
            "tenant_id": payload["tenant_id"],
            "user_id": payload["sub"],
        }
    except Exception:
        raise unauthorized(detail="Invalid token")
